CREATE TABLE LojaFisica (
	CNPJ BIGINT NOT NULL,
	Fundacao DATE NOT NULL,
	CEP BIGINT NOT NULL,
	AcessivelDeficientes TINYINT(1) NOT NULL,
	PRIMARY KEY (CNPJ)
);

CREATE TABLE Estoque (
	IdEstoque INT NOT NULL AUTO_INCREMENT,
	Capacidade INT NOT NULL,
	AreaTotal INT NOT NULL,
	CNPJ_Loja BIGINT NOT NULL,
	PRIMARY KEY (IdEstoque),
	FOREIGN KEY (CNPJ_Loja) REFERENCES LojaFisica(CNPJ)
);

CREATE TABLE Produto (
	IdProduto INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(255) NOT NULL,
	Tipo VARCHAR(255) NOT NULL,
	Preco DECIMAL(15, 2) NOT NULL,
	PRIMARY KEY (IdProduto)
);

CREATE TABLE Funcionario (
	RG BIGINT NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	DataAdmissao DATE NOT NULL,
	Genero VARCHAR(255) NOT NULL,
	CNPJ_Loja BIGINT NOT NULL,
	PRIMARY KEY (RG),
	FOREIGN KEY (CNPJ_Loja) REFERENCES LojaFisica(CNPJ)
);

CREATE TABLE Cliente (
	RG BIGINT NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	Genero VARCHAR(255) NOT NULL,
	PRIMARY KEY (RG)
);

CREATE TABLE Pedido (
	IdPedido INT NOT NULL AUTO_INCREMENT,
	Data DATETIME DEFAULT NOW(),
	Preco DECIMAL(15, 2) NOT NULL,
	CNPJ_Loja BIGINT NOT NULL,
	RG_Cliente BIGINT NOT NULL,
	PRIMARY KEY (IdPedido),
	FOREIGN KEY (CNPJ_Loja) REFERENCES LojaFisica(CNPJ),
	FOREIGN KEY (RG_Cliente) REFERENCES Cliente(RG)
);

CREATE TABLE Armazena (
	IdEstoque INT NOT NULL,
	IdProduto INT NOT NULL,
	Quantidade INT NOT NULL,
	FOREIGN KEY (IdEstoque) REFERENCES Estoque(IdEstoque),
	FOREIGN KEY (IdProduto) REFERENCES Produto(IdProduto)
);

CREATE TABLE Tem (
	IdPedido INT NOT NULL,
	IdProduto INT NOT NULL,
	Quantidade INT NOT NULL,
	FOREIGN KEY (IdPedido) REFERENCES Pedido(IdPedido),
	FOREIGN KEY (IdProduto) REFERENCES Produto(IdProduto)
);
